package authenticationadmin;

import javax.swing.JOptionPane;

/**
 * View Section of Admin Panel it is Created by Netbeans IDE
 *
 * @author Keyvan Derakhshan Nik
 */
public class AuthenticationAdminView extends javax.swing.JFrame {

    /**
     * Creates new form AuthenticationAdminView
     */
    public AuthenticationAdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        First = new javax.swing.JPanel();
        ipText = new javax.swing.JTextField();
        portText = new javax.swing.JTextField();
        userNameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        Second = new javax.swing.JPanel();
        AdminPane = new javax.swing.JTabbedPane();
        CreateUser = new javax.swing.JPanel();
        North = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        Center = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox();
        South = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        Report = new javax.swing.JPanel();
        ReportHeader = new javax.swing.JPanel();
        onLineUsers = new javax.swing.JButton();
        serverLogFile = new javax.swing.JButton();
        serverInformation = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        ReportText = new javax.swing.JPanel();
        reportText = new javax.swing.JScrollPane();
        reporiText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 400));
        setResizable(false);

        First.setBorder(new javax.swing.border.MatteBorder(null));
        First.setName(""); // NOI18N
        First.setPreferredSize(new java.awt.Dimension(900, 50));
        First.setLayout(new java.awt.GridLayout(1, 0));

        ipText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ipText.setText("Enter Server IP");
        ipText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipTextMouseClicked(evt);
            }
        });
        First.add(ipText);

        portText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        portText.setText("Enter Server Port");
        portText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                portTextFocusGained(evt);
            }
        });
        First.add(portText);

        userNameText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNameText.setText("Enter UserName");
        userNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTextFocusGained(evt);
            }
        });
        First.add(userNameText);

        passwordText.setToolTipText("Password");
        First.add(passwordText);

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        First.add(login);

        Second.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Second.setPreferredSize(new java.awt.Dimension(900, 300));

        AdminPane.setFont(new java.awt.Font("Segoe Script", 2, 14)); // NOI18N

        CreateUser.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("UserName:   ");

        jLabel2.setText("Password:");

        javax.swing.GroupLayout NorthLayout = new javax.swing.GroupLayout(North);
        North.setLayout(NorthLayout);
        NorthLayout.setHorizontalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        NorthLayout.setVerticalGroup(
            NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorthLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(NorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        CreateUser.add(North, java.awt.BorderLayout.PAGE_START);

        jLabel3.setText("Role:");

        roleComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roleComboBox.setMaximumRowCount(2);
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "operator" }));

        javax.swing.GroupLayout CenterLayout = new javax.swing.GroupLayout(Center);
        Center.setLayout(CenterLayout);
        CenterLayout.setHorizontalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        CenterLayout.setVerticalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CreateUser.add(Center, java.awt.BorderLayout.CENTER);

        createButton.setText("Create");
        createButton.setActionCommand("create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SouthLayout = new javax.swing.GroupLayout(South);
        South.setLayout(SouthLayout);
        SouthLayout.setHorizontalGroup(
            SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SouthLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(createButton)
                .addGap(194, 194, 194)
                .addComponent(exitButton)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        SouthLayout.setVerticalGroup(
            SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SouthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(exitButton))
                .addGap(35, 35, 35))
        );

        CreateUser.add(South, java.awt.BorderLayout.PAGE_END);

        AdminPane.addTab("Create User", CreateUser);

        Report.setLayout(new java.awt.BorderLayout());

        onLineUsers.setText("On Line Users");
        onLineUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLineUsersActionPerformed(evt);
            }
        });

        serverLogFile.setText("Server Log File");
        serverLogFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverLogFileActionPerformed(evt);
            }
        });

        serverInformation.setText("Server Information");
        serverInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverInformationActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportHeaderLayout = new javax.swing.GroupLayout(ReportHeader);
        ReportHeader.setLayout(ReportHeaderLayout);
        ReportHeaderLayout.setHorizontalGroup(
            ReportHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportHeaderLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(onLineUsers)
                .addGap(101, 101, 101)
                .addComponent(serverLogFile)
                .addGap(91, 91, 91)
                .addComponent(serverInformation)
                .addGap(97, 97, 97)
                .addComponent(exit)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        ReportHeaderLayout.setVerticalGroup(
            ReportHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportHeaderLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ReportHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onLineUsers)
                    .addComponent(serverLogFile)
                    .addComponent(serverInformation)
                    .addComponent(exit))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        Report.add(ReportHeader, java.awt.BorderLayout.PAGE_START);

        reporiText.setColumns(20);
        reporiText.setRows(5);
        reportText.setViewportView(reporiText);

        javax.swing.GroupLayout ReportTextLayout = new javax.swing.GroupLayout(ReportText);
        ReportText.setLayout(ReportTextLayout);
        ReportTextLayout.setHorizontalGroup(
            ReportTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportText, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
                .addContainerGap())
        );
        ReportTextLayout.setVerticalGroup(
            ReportTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportText, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Report.add(ReportText, java.awt.BorderLayout.CENTER);

        AdminPane.addTab("Report", Report);

        javax.swing.GroupLayout SecondLayout = new javax.swing.GroupLayout(Second);
        Second.setLayout(SecondLayout);
        SecondLayout.setHorizontalGroup(
            SecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminPane, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SecondLayout.setVerticalGroup(
            SecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondLayout.createSequentialGroup()
                .addComponent(AdminPane, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addComponent(Second, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                .addGap(106, 106, 106))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Second, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        First.getAccessibleContext().setAccessibleName("FirstPannel");

        getContentPane().add(Main, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if (new AuthenticationAdminControl().checkFileds(ipText.getText(), portText.getText(), userNameText.getText(), passwordText.getText())) {
            First.setVisible(false);
            Second.setVisible(true);
        }

    }//GEN-LAST:event_loginActionPerformed
    private void ipTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipTextMouseClicked
        ipText.setText("");
    }//GEN-LAST:event_ipTextMouseClicked
    private void portTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_portTextFocusGained
        portText.setText("");
    }//GEN-LAST:event_portTextFocusGained
    private void userNameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFocusGained
        userNameText.setText("");
    }//GEN-LAST:event_userNameTextFocusGained
    private void serverLogFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverLogFileActionPerformed
        reporiText.setText("");
        String result = new AuthenticationAdminModel().sendRequest("serverLog");
        String[] inputSplitNewLine = result.split("\\t");
        for (int i = 0; i < inputSplitNewLine.length; i++) {
            reporiText.append("\n" + inputSplitNewLine[i] + "\n");
        }
    }//GEN-LAST:event_serverLogFileActionPerformed
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        new AuthenticationAdminModel().sendRequest("close");
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        String s = new AuthenticationAdminModel().sendRequest("close");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if (new AuthenticationAdminControl().checkNewUser(userName.getText(), password.getText())) {
            String result = new AuthenticationAdminModel().sendRequest("<newUser>" + userName.getText() + "</newUser>" + "<newPassword>" + password.getText() + "</newPassword>" + "<newRole>" + roleComboBox.getItemAt(roleComboBox.getSelectedIndex()) + "</newRole>");
            JOptionPane.showMessageDialog(null, result);
        }
    }//GEN-LAST:event_createButtonActionPerformed
    private void onLineUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLineUsersActionPerformed
        reporiText.setText("");
        String result = new AuthenticationAdminModel().sendRequest("onLineUsers");
        String[] inputSplitNewLine = result.split("\\t");
        for (String inputSplitNewLine1 : inputSplitNewLine) {
            reporiText.append("\n" + inputSplitNewLine1 + "\n");
        }
    }//GEN-LAST:event_onLineUsersActionPerformed
    private void serverInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverInformationActionPerformed
        reporiText.setText("");
        String result = new AuthenticationAdminModel().sendRequest("serverInfo");
        String[] inputSplitNewLine = result.split("\\t");
        for (String inputSplitNewLine1 : inputSplitNewLine) {
            reporiText.append("\n" + inputSplitNewLine1 + "\n");
        }
    }//GEN-LAST:event_serverInformationActionPerformed
    public void view() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AuthenticationAdminView pannel = new AuthenticationAdminView();
                pannel.setVisible(true);
                pannel.First.setVisible(true);
                pannel.Second.setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminPane;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel CreateUser;
    private javax.swing.JPanel First;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel North;
    private javax.swing.JPanel Report;
    private javax.swing.JPanel ReportHeader;
    private javax.swing.JPanel ReportText;
    private javax.swing.JPanel Second;
    private javax.swing.JPanel South;
    private javax.swing.JButton createButton;
    private javax.swing.JButton exit;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField ipText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JButton onLineUsers;
    private javax.swing.JTextField password;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField portText;
    private javax.swing.JTextArea reporiText;
    private javax.swing.JScrollPane reportText;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JButton serverInformation;
    private javax.swing.JButton serverLogFile;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
