package authenticationclient;
/**
 * View Section of Client Panel it is Created by Netbeans IDE
 *
 * @author Keyvan Derakhshan Nik
 */
public class AuthenticationClientView extends javax.swing.JFrame {
    /**
     * Creates new form for client side
     */
    public AuthenticationClientView() {
        initComponents();
    }
    /**
     * this part generated by IDE Pallet .
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserNamePanel = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        PasswordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        ControlPanel = new javax.swing.JPanel();
        authenticateJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Authentication Application");
        setPreferredSize(new java.awt.Dimension(600, 150));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        UserNamePanel.setPreferredSize(new java.awt.Dimension(500, 60));
        UserNamePanel.setLayout(new java.awt.GridBagLayout());

        userNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userNameLabel.setText("User Name:");
        UserNamePanel.add(userNameLabel, new java.awt.GridBagConstraints());

        userNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userNameJTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userNameJTextField.setNextFocusableComponent(jPasswordField);
        userNameJTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });
        UserNamePanel.add(userNameJTextField, new java.awt.GridBagConstraints());

        getContentPane().add(UserNamePanel);

        PasswordPanel.setPreferredSize(new java.awt.Dimension(500, 60));
        PasswordPanel.setLayout(new java.awt.GridBagLayout());

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordLabel.setText("Password:");
        passwordLabel.setPreferredSize(new java.awt.Dimension(71, 17));
        PasswordPanel.add(passwordLabel, new java.awt.GridBagConstraints());

        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField.setNextFocusableComponent(authenticateJButton);
        jPasswordField.setPreferredSize(new java.awt.Dimension(100, 30));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        PasswordPanel.add(jPasswordField, new java.awt.GridBagConstraints());

        getContentPane().add(PasswordPanel);

        ControlPanel.setPreferredSize(new java.awt.Dimension(500, 60));
        ControlPanel.setLayout(new java.awt.GridBagLayout());

        authenticateJButton.setText("Authenticate");
        authenticateJButton.setToolTipText("check username and password");
        authenticateJButton.setNextFocusableComponent(clearJButton);
        authenticateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticateJButtonActionPerformed(evt);
            }
        });
        ControlPanel.add(authenticateJButton, new java.awt.GridBagConstraints());

        clearJButton.setText("Clear");
        clearJButton.setToolTipText("clear boxes");
        clearJButton.setNextFocusableComponent(userNameJTextField);
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });
        ControlPanel.add(clearJButton, new java.awt.GridBagConstraints());

        getContentPane().add(ControlPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
    
    }//GEN-LAST:event_userNameJTextFieldActionPerformed
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // make Clear Text Fields
        initial(); 
    }//GEN-LAST:event_clearJButtonActionPerformed
    private void authenticateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticateJButtonActionPerformed
        /*
        *send information to Control section for validation
        *if data is not valid it must initial again
        */
        AuthenticationClientControl control=new AuthenticationClientControl();
        if(!control.verify(getUserNameJTextField(),getjPasswordField()))
        initial();
    }//GEN-LAST:event_authenticateJButtonActionPerformed
    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
    }//GEN-LAST:event_jPasswordFieldActionPerformed
    /**
     * Initial text fields
     */
    void initial(){
        setUserNameJTextField("");
        setjPasswordField("");
    }
    /**
     * start part of view section
     */
      void view() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /**
         * Create and display the form 
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthenticationClientView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JPanel UserNamePanel;
    private javax.swing.JButton authenticateJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
    /**
     * getter for UserName Text Field 
     */
    public String getUserNameJTextField() {
        return userNameJTextField.getText();
    }
    /**
     * setter for UserName Text Field 
     */
    public void setUserNameJTextField(String userNameJTextField) {
        this.userNameJTextField.setText(userNameJTextField);
    }
    /**
     * getter for Password Text Field 
     */
    public String getjPasswordField() {
        return jPasswordField.getText();
    }
    /**
     * setter for Password Text Field 
     */
    public void setjPasswordField(String jPasswordField) {
        this.jPasswordField.setText(jPasswordField);
    }
}
